### ISSUE TITLE
Submit "ytt" as plugin into asdf-plugins

### ISSUE THREAD

**Issue by MPV** [johnhamelink/asdf-k14s#1]
Hi,
Could we add `ytt` as a proper plugin in asdf-plugins?

So this works:

```shell
$ asdf plugin add ytt
plugin ytt not found in repository
```

```shell
$ asdf plugin list all | grep ytt | wc -l
       0
```

**Comment by MPV** [comment]
Is there a `plugins/ytt` file missing in the `asdf-plugins` repo?

I noticed that `k14s` was added as a plugin in https://github.com/asdf-vm/asdf-plugins/pull/224/files

But only a `plugins/k14s` file, but no separate files for each of the sub-plugins (?).

**Comment by MPV** [comment]
I made a PR here, does that seem right?
https://github.com/asdf-vm/asdf-plugins/pull/313

**Comment by cppforlife** [comment]
> I made a PR here, does that seem right?

hey @MPV, im guessing you are more knowledgeable in asdf area than i am since im not a regular user. let's see what happens with you PR.

**Comment by neil-hickey** [comment]
done as part of https://github.com/asdf-vm/asdf-plugins/pull/313
