### ISSUE TITLE
installation error "Couldn't find remote ref master"

### ISSUE THREAD

**Issue by yogeek** [johnhamelink/asdf-k14s#2]
Hello,

You only have `develop` branch in github, and asdf seems to search for master branch

```
$ asdf plugin add kapp https://github.com/k14s/asdf-k14s.git

$ asdf plugin list --urls | grep kapp
kapp                         https://github.com/k14s/asdf-k14s.git

$  asdf plugin update kapp 
Updating kapp...
fatal: Couldn't find remote ref master
```

Is there someting I missed ?

**Comment by cppforlife** [comment]
@yogeek it looks like asdf hard coded master branch as default instead of relying on git to provide one. 

related: https://github.com/asdf-vm/asdf/issues/799

**Comment by cppforlife** [comment]
flipped back this repo to use `master` branch until asdf can work with other default branches.

**Comment by yogeek** [comment]
@cppforlife thanks but still does not work. I opened a PR : #3

**Comment by jthegedus** [comment]
Sorry about this, solution should be in soon.
